### PR TITLE
Add queue randomization (#147)

### PR DESCRIPTION
**Pull request by tonyb7**
Add queue randomization as suggested in #147. 

I am having a bit of trouble setting up the server locally to test my changes, as I am getting 

>ActiveRecord::PendingMigrationError
Migrations are pending. To resolve this issue, run: bin/rails db:migrate RAILS_ENV=development

but I figured I would open this PR to get some feedback, and to see if I could get help with testing and a couple questions I had. I am currently unsure about two changes:

1) I am not familiar at all with  ruby, so I am guessing the way you shuffle the outstanding requests is by doing `@course_queue.outstanding_requests.shuffle` ([code here](https://github.com/mterwill/office-hours-help-queue/pull/207/files#diff-2f2e9f0a48ea80906d8bd5482db99a611b2640ff6b5735485da5306738232393R126)), but again I haven't been able to test this, and I am not sure if there are other metadata which also need to be shuffled around.

2) I am not positive if calling `course_queue`'s `broadcastInstructorMessage` from `instructor_panel` will work ([code here](https://github.com/mterwill/office-hours-help-queue/pull/207/files#diff-12f97d7cdbf3e8b96b2d1a746613ff4e6e330bd6978ff4da0679d833385551cfR43)). My intention is to send a notification to students whenever the queue is randomized.

Thanks for any help anyone can provide!

### CODE REVIEW

**Comment by thomasebsmith** [comment]
To fix the migrations error, I was able to start the container and then run
```sh
$ docker-compose run web bash
# root@...:/usr/src/eecshelp# bin/rails db:migrate RAILS_ENV=development
```

**Comment by thomasebsmith** [comment]
I think the shuffle also needs to be a little more complicated. It looks like the outstanding requests are stored as rows in the `course_queue_entries` table. They are then always displayed ordered by the `created_at` column (when the request was created).

To randomize these requests, I think we'd need to either rewrite all the `created_at` times (which isn't great) or add another column to the table to store a custom order.

**Comment by tonyb7** [comment]
Thanks Thomas! Got the queue running locally now. You're right -- the shuffling is not working, so there's more that needs to be changed there.

Also, what is the best way to test notifications to students? Currently I'm just opening the queue on multiple browsers and signing up as a student. However, my student browser is not receiving notifications even when the instructor broadcasts a message. Is there a better way to test multiple users (from the instructor's perspective as well as the student's perspective at the same time) other than with multiple browsers?

**Comment by thomasebsmith** [comment]
I've only been able to test with multiple browsers (or the same browser with one user in private browsing mode). For me, broadcasting from one browser/window does bring up an alert in other browsers/windows.

**Comment by thomasebsmith** [comment]
I've implemented a version of randomization that seems to work. More manual testing is required, and I haven't written any automated tests yet. I'd also like feedback on whether the way I implemented it seems like the best way to do it.

How it works:
- There is a new column in the `course_queue_entries` table, `priority`.
- Requests are now sorted by `priority` and then `created_at`.
- New requests have a priority of 0, so they are added to the bottom of the queue as usual.
- Clicking the "Randomize Queue" button randomly assigns priorities such that all unresolved requests are now in a random order.
- Users with unpinned requests are notified if their position in the unpinned section of the queue changes.

**Comment by mterwill** [comment]
👋 thanks for the contribution! Sorry for the super long delay in reviewing this. 💭 on #216 as potential alternative?

**Comment by tonyb7** [comment]
I think the solution in #216 looks good too! It's a more systematic solution than the one in this PR.

**Comment by mterwill** [comment]
Closing in favor of https://github.com/mterwill/office-hours-help-queue/pull/216. Thanks for your contribution!

**Pull request closed without merging**
