### PR TITLE
Increase max length on student request location field

### LINKED ISSUE #185: Long locations get cut off
482 uses the queue location for virtual office hours, and we encourage students to paste a join link for their Google Meet or Zoom meeting in the location field of their request. However, some of these links (especially Zoom meetings with encrypted passcodes) can get very long and are cut off in the request location, preventing us from joining the meeting. Could the location field be extended so longer URLs can fit?

### PR DESCRIPTION
**Pull request by akiekintveld**
Closes #185.

### CODE REVIEW

**Comment by mterwill** [comment]
👋 thanks @akiekintveld for the contribution!

Currently, this will overflow with long locations.

image

What do you think about truncating the long text with some CSS? We could do something like this in `LabeledItem`:

```
          <div style={{ maxWidth: '50ch', textOverflow: 'ellipsis', overflow: 'hidden' }}>
          {this.props.children}
          </div>
```

A double click/copy/paste (or a click on the link if starts with `https`) preserves the entire field.

**Comment by akiekintveld** [comment]
Oh, weird, when I tested it out (in Safari 14, Chrome 85, and Firefox 81), it was wrapping the text, which looked fine. I also like how the ellipses look though, seems to work well (had to add `whiteSpace: 'nowrap'` as well otherwise it kept wrapping).

**Review by mterwill — APPROVED** [review]

**Comment by akiekintveld** [comment]
I see there's a check expected before this can be merged, do I need to do something to get that to run?

**Comment by mterwill** [comment]
Fixed in #187

**Comment by mterwill** [comment]
Deployed!

**Pull request merged**
