### PR TITLE
Add 'Force Anonymous' Mode

### PR DESCRIPTION
**Pull request by sletap**
Anonymous mode prevents students from seeing each other on the queue. Instructors will still be able to see everyone as normal. This mode can be toggled on a per queue basis in the admin panel. Solves issue #69

### CODE REVIEW

**Comment by mterwill** [comment]
Hey @sletap, thanks for the PR! I pulled it down and played around a bit. I noticed that a user's request shows as anonymous to themselves too, which could be confusing. Thoughts on showing your own request in the queue normally, even in anonymous mode?

Also curious if you considered implementing the information hiding server-side instead. As you have it now, a student could break the anonymity of their peers by peeking at the underlying data structure, by, for example, using [react devtools](https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi?hl=en).

**Comment by sletap** [comment]
Hey! Yeah if it's your own request I also think you should be able to see yourself, I'll apply that change soon!

As for breaking anonymity, that's a good point as well. Do you have pointers on how I would go about doing this?

**Comment by mterwill** [comment]
👋 awesome, thanks! The logic that passes request information to clients is mostly in [`queue_channel.rb`](https://github.com/mterwill/office-hours-help-queue/blob/master/app/channels/queue_channel.rb). In particular, this method might be a good place to start:

https://github.com/mterwill/office-hours-help-queue/blob/5e84329aa3011e421d9e2101e2ed62077c8ede96/app/channels/queue_channel.rb#L142-L147

Perhaps we could add a new anonymous serializer that's invoked conditionally.

One other thing to consider: I'm not sure what assumptions might break depending on how much information is stripped out in anonymizing requests. For example, how does the frontend behave without a `requester_id` on a request?

**Comment by mterwill** [comment]
@sletap bump. Are you still interested in getting this PR merged?

**Comment by sletap** [comment]
@mterwill I've been pretty busy so I don't think I'll be able to! If someone else wants to take on the rest of it that's totally fine!

**Comment by mterwill** [comment]
👍 thanks! I'll go ahead and close this out for now. Feel free to re-open.

**Pull request closed without merging**
